background #0a506e
foreground #e5dccb

cursor #e5dccb
selection_background #1d1f21
selection_foreground #e5dccb

color8 #cc8f62

color10 #24dcd4

color11 #d19742

color12 #66a1b8
color13 #e35b22

color14 #cc8f62

color15 #58c5cd

background_opacity 1

color3 #FFD300
color1 #FF4500

color7 #cc8f62

active_border_color #1d1f21

confirm_os_window_close 0
