background #22303c
foreground #E6D5B8

cursor #E6D5B8
selection_background #1B263B
selection_foreground #E6D5B8

color0  #0D1B2A
color1  #CC6E2E
color2  #00D2C3
color3  #C28840
color4  #415A77
color5  #48C4F8
color6  #00D2C3
color7  #E6D5B8

color8  #6C7A89
color9  #F05A22
color10 #48C4F8
color11 #DDAA33
color12 #6C7A89
color13 #C28840
color14 #00D2C3
color15 #CFC8B5

background_opacity 1
active_border_color #415A77
confirm_os_window_close 0
font_size 13.0
font_family FiraCode Nerd Font Mono
adjust_line_height 2
adjust_column_width 0
enable_ligatures always
