background #22303c
foreground #E6D5B8

cursor #E6D5B8
selection_background #1B263B
selection_foreground #E6D5B8

color0  #0D1B2A
color1  #CC6E2E
color2  #00d2c3
color3  #DDAA33
color4  #c79a2b
color5  #48c4f8
color6  #f7941e
color7  #E6D5B8

color8  #6C7A89
color9  #A65A2E
color10 #48c4f8
color11 #E1B955
color12 #6C7A89
color13 #C79A2B
color14 #00d2c3
color15 #CFC8B5

background_opacity 1
active_border_color #1B263B
confirm_os_window_close 0
font_size 13.0
font_family FiraCode Nerd Font Mono
adjust_line_height 2
adjust_column_width 0
enable_ligatures always
